# Generated by Django 4.1.3 on 2022-11-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_alter_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
