# Generated by Django 4.1.3 on 2022-11-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seller_alter_category_name_item_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='staff_1',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
