# Generated by Django 4.1.3 on 2022-11-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seller_staff_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='staff_1',
        ),
    ]
