# Generated by Django 4.1.3 on 2022-11-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_seller_staff_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='author',
            new_name='name',
        ),
    ]
