# Generated by Django 4.1.3 on 2022-12-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_brand_collection_alter_item_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wished_item',
        ),
        migrations.AddField(
            model_name='item',
            name='user_wishlist',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to='core.userprofile'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
