# Generated by Django 4.1.3 on 2022-12-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_item_user_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='author',
            new_name='seller',
        ),
    ]
