# Generated by Django 4.1.3 on 2022-12-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_homepromotion_rename_author_item_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
