# Generated by Django 4.1.3 on 2022-12-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_seller_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='name',
            new_name='user',
        ),
    ]
