# Generated by Django 4.1.3 on 2022-12-17 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_alter_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
