# Generated by Django 4.1.3 on 2022-12-21 13:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_brand_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to=''),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepromotion',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_3',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_main',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to=''),
        ),
    ]
