# Generated by Django 4.1.3 on 2022-12-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_brand_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepromotion',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.brand'),
        ),
        migrations.AddField(
            model_name='homepromotion',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.collection'),
        ),
    ]
