# Generated by Django 4.1.3 on 2022-12-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_homepromotion_brand_homepromotion_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepromotion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.category'),
        ),
    ]
