# Generated by Django 4.1.3 on 2023-01-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_item_seller_item_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepromotion',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
