# Generated by Django 4.1.3 on 2023-01-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_homebanner_remove_homepromotion_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='banner_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
