# Generated by Django 4.1.3 on 2023-01-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_item_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='depth',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
