# Generated by Django 4.1.3 on 2023-01-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_brand_banner_image_category_banner_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='banner_image',
            new_name='banner',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='banner_image',
            new_name='banner',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='banner_image',
            new_name='banner',
        ),
    ]
