# Generated by Django 4.1.3 on 2023-01-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename_banner_image_brand_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='city', max_length=115),
        ),
    ]
