# Generated by Django 4.1.3 on 2023-01-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=115, null=True),
        ),
    ]
