# Generated by Django 4.1.3 on 2023-01-17 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0048_item_created_at_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('al', 'aliceblue'), ('an', 'antiquewhite'), ('aq', 'aqua'), ('au', 'aquamarine'), ('az', 'azure'), ('be', 'beige'), ('bi', 'bisque'), ('bl', 'black'), ('ba', 'blanchedalmond'), ('bu', 'blue'), ('bn', 'blueviolet'), ('br', 'brown'), ('by', 'burlywood'), ('ca', 'cadetblue'), ('ch', 'chartreuse'), ('co', 'chocolate'), ('cr', 'coral'), ('cn', 'cornflowerblue'), ('cs', 'cornsilk'), ('ci', 'crimson'), ('cy', 'cyan'), ('da', 'darkblue'), ('d', 'darkcyan'), ('dg', 'darkgoldenrod'), ('dr', 'darkgray'), ('de', 'darkgrey'), ('dn', 'darkgreen'), ('dk', 'darkkhaki'), ('dm', 'darkmagenta'), ('dl', 'darkolivegreen'), ('do', 'darkorange'), ('dh', 'darkorchid'), ('dd', 'darkred'), ('ds', 'darksalmon'), ('dz', 'darkseagreen'), ('db', 'darkslateblue'), ('dy', 'darkslategray'), ('di', 'darkslategrey'), ('du', 'darkturquoise'), ('dv', 'darkviolet'), ('dp', 'deeppink'), ('dx', 'deepskyblue'), ('dc', 'dimgray'), ('dn', 'dimgrey'), ('dq', 'dodgerblue'), ('fa', 'firebrick'), ('fb', 'floralwhite'), ('fc', 'forestgreen'), ('fd', 'fuchsia'), ('ga', 'gainsboro'), ('gb', 'ghostwhite'), ('gc', 'gold'), ('gd', 'goldenrod'), ('ge', 'gray'), ('gf', 'grey'), ('gg', 'green'), ('gh', 'greenyellow'), ('ha', 'honeydew'), ('hb', 'hotpink'), ('hc', 'indianred'), ('hd', 'indigo'), ('he', 'ivory'), ('hf', 'khaki'), ('la', 'lavender'), ('lb', 'lavenderblush'), ('lc', 'lawngreen'), ('ld', 'lemonchiffon'), ('le', 'lightblue'), ('lf', 'lightcoral'), ('lg', 'lightcyan'), ('lh', 'lightgoldenrodyellow'), ('li', 'lightgray'), ('lj', 'lightgrey'), ('ll', 'lightgreen'), ('lk', 'lightpink'), ('lm', 'lightsalmon'), ('ln', 'lightseagreen'), ('lo', 'lightskyblue'), ('lp', 'lightslategray'), ('lq', 'lightslategrey'), ('lr', 'lightsteelblue'), ('ls', 'lightyellow'), ('lt', 'lime'), ('lu', 'limegreen'), ('lv', 'linen'), ('ma', 'magenta'), ('mb', 'maroon'), ('mc', 'mediumaquamarine'), ('md', 'mediumblue'), ('me', 'mediumorchid'), ('mf', 'mediumpurple'), ('mg', 'mediumseagreen'), ('mh', 'mediumslateblue'), ('mi', 'mediumspringgreen'), ('mj', 'mediumturquoise'), ('mk', 'mediumvioletred'), ('ml', 'midnightblue'), ('mm', 'mintcream'), ('mn', 'mistyrose'), ('mo', 'moccasin'), ('na', 'navajowhite'), ('nb', 'navy'), ('oa', 'oldlace'), ('ob', 'olive'), ('oc', 'olivedrab'), ('od', 'orange'), ('oe', 'orangered'), ('of', 'orchid'), ('og', 'palegoldenrod'), ('oh', 'palegreen'), ('oi', 'paleturquoise'), ('oj', 'palevioletred'), ('ok', 'papayawhip'), ('ol', 'peachpuff'), ('om', 'peru'), ('on', 'pink'), ('oo', 'plum'), ('op', 'powderblue'), ('oq', 'purple'), ('or', 'red'), ('os', 'rosybrown'), ('ot', 'royalblue'), ('sa', 'saddlebrown'), ('sb', 'salmon'), ('sc', 'sandybrown'), ('sd', 'seagreen'), ('se', 'seashell'), ('sf', 'sienna'), ('sg', 'silver'), ('si', 'skyblue'), ('sj', 'slateblue'), ('sk', 'slategray'), ('sl', 'slategrey'), ('sm', 'snow'), ('sn', 'springgreen'), ('so', 'steelblue'), ('ta', 'tan'), ('tb', 'teal'), ('tc', 'thistle'), ('td', 'tomato'), ('te', 'turquoise'), ('va', 'violet'), ('wa', 'wheat'), ('wb', 'white'), ('wc', 'whitesmoke'), ('ya', 'yellow'), ('yb', 'yellowgreen')], max_length=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='core.item')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
