# Generated by Django 4.1.3 on 2023-01-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_comment_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('facebook', models.CharField(max_length=25)),
                ('instagram', models.CharField(max_length=25)),
                ('twitter', models.CharField(max_length=25)),
                ('youtube', models.CharField(max_length=25)),
                ('linkedin', models.CharField(max_length=25)),
            ],
        ),
    ]
