# Generated by Django 4.1.3 on 2023-01-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_footerdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerdetail',
            name='facebook',
            field=models.CharField(max_length=115),
        ),
        migrations.AlterField(
            model_name='footerdetail',
            name='instagram',
            field=models.CharField(max_length=115),
        ),
        migrations.AlterField(
            model_name='footerdetail',
            name='linkedin',
            field=models.CharField(max_length=115),
        ),
        migrations.AlterField(
            model_name='footerdetail',
            name='twitter',
            field=models.CharField(max_length=115),
        ),
        migrations.AlterField(
            model_name='footerdetail',
            name='youtube',
            field=models.CharField(max_length=115),
        ),
    ]
