# Generated by Django 4.1.3 on 2023-03-01 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0056_shippingcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_main',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('aliceblue', 'aliceblue'), ('antiquewhite', 'antiquewhite'), ('aqua', 'aqua'), ('aquamarine', 'aquamarine'), ('azure', 'azure'), ('beige', 'beige'), ('bisque', 'bisque'), ('black', 'black'), ('blanchedalmond', 'blanchedalmond'), ('blue', 'blue'), ('blueviolet', 'blueviolet'), ('brown', 'brown'), ('burlywood', 'burlywood'), ('cadetblue', 'cadetblue'), ('chartreuse', 'chartreuse'), ('chocolate', 'chocolate'), ('coral', 'coral'), ('cornflowerblue', 'cornflowerblue'), ('cornsilk', 'cornsilk'), ('crimson', 'crimson'), ('cyan', 'cyan'), ('darkblue', 'darkblue'), ('darkcyan', 'darkcyan'), ('darkgoldenrod', 'darkgoldenrod'), ('darkgray', 'darkgray'), ('darkgrey', 'darkgrey'), ('darkgreen', 'darkgreen'), ('darkkhaki', 'darkkhaki'), ('darkmagenta', 'darkmagenta'), ('darkolivegreen', 'darkolivegreen'), ('darkorange', 'darkorange'), ('darkorchid', 'darkorchid'), ('darkred', 'darkred'), ('darksalmon', 'darksalmon'), ('darkseagreen', 'darkseagreen'), ('darkslateblue', 'darkslateblue'), ('darkslategray', 'darkslategray'), ('darkslategrey', 'darkslategrey'), ('darkturquoise', 'darkturquoise'), ('darkviolet', 'darkviolet'), ('deeppink', 'deeppink'), ('deepskyblue', 'deepskyblue'), ('dimgray', 'dimgray'), ('dimgrey', 'dimgrey'), ('dodgerblue', 'dodgerblue'), ('firebrick', 'firebrick'), ('floralwhite', 'floralwhite'), ('forestgreen', 'forestgreen'), ('fuchsia', 'fuchsia'), ('gainsboro', 'gainsboro'), ('ghostwhite', 'ghostwhite'), ('gold', 'gold'), ('goldenrod', 'goldenrod'), ('gray', 'gray'), ('grey', 'grey'), ('green', 'green'), ('greenyellow', 'greenyellow'), ('honeydew', 'honeydew'), ('hotpink', 'hotpink'), ('indianred', 'indianred'), ('indigo', 'indigo'), ('ivory', 'ivory'), ('khaki', 'khaki'), ('lavender', 'lavender'), ('lavenderblush', 'lavenderblush'), ('lawngreen', 'lawngreen'), ('lemonchiffon', 'lemonchiffon'), ('lightblue', 'lightblue'), ('lightcoral', 'lightcoral'), ('lightcyan', 'lightcyan'), ('lightgoldenrodyellow', 'lightgoldenrodyellow'), ('lightgray', 'lightgray'), ('lightgrey', 'lightgrey'), ('lightgreen', 'lightgreen'), ('lightpink', 'lightpink'), ('lightsalmon', 'lightsalmon'), ('lightseagreen', 'lightseagreen'), ('lightskyblue', 'lightskyblue'), ('lightslategray', 'lightslategray'), ('lightslategrey', 'lightslategrey'), ('lightsteelblue', 'lightsteelblue'), ('lightyellow', 'lightyellow'), ('lime', 'lime'), ('limegreen', 'limegreen'), ('linen', 'linen'), ('magenta', 'magenta'), ('maroon', 'maroon'), ('mediumaquamarine', 'mediumaquamarine'), ('mediumblue', 'mediumblue'), ('mediumorchid', 'mediumorchid'), ('mediumpurple', 'mediumpurple'), ('mediumseagreen', 'mediumseagreen'), ('mediumslateblue', 'mediumslateblue'), ('mediumspringgreen', 'mediumspringgreen'), ('mediumturquoise', 'mediumturquoise'), ('mediumvioletred', 'mediumvioletred'), ('midnightblue', 'midnightblue'), ('mintcream', 'mintcream'), ('mistyrose', 'mistyrose'), ('moccasin', 'moccasin'), ('navajowhite', 'navajowhite'), ('navy', 'navy'), ('oldlace', 'oldlace'), ('olive', 'olive'), ('oc', 'olivedrab'), ('orange', 'orange'), ('orangered', 'orangered'), ('orchid', 'orchid'), ('palegoldenrod', 'palegoldenrod'), ('palegreen', 'palegreen'), ('paleturquoise', 'paleturquoise'), ('palevioletred', 'palevioletred'), ('papayawhip', 'papayawhip'), ('peachpuff', 'peachpuff'), ('peru', 'peru'), ('pink', 'pink'), ('plum', 'plum'), ('powderblue', 'powderblue'), ('purple', 'purple'), ('red', 'red'), ('rosybrown', 'rosybrown'), ('royalblue', 'royalblue'), ('saddlebrown', 'saddlebrown'), ('salmon', 'salmon'), ('sandybrown', 'sandybrown'), ('seagreen', 'seagreen'), ('seashell', 'seashell'), ('sienna', 'sienna'), ('silver', 'silver'), ('skyblue', 'skyblue'), ('slateblue', 'slateblue'), ('slategray', 'slategray'), ('slategrey', 'slategrey'), ('snow', 'snow'), ('springgreen', 'springgreen'), ('steelblue', 'steelblue'), ('tan', 'tan'), ('teal', 'teal'), ('thistle', 'thistle'), ('tomato', 'tomato'), ('turquoise', 'turquoise'), ('violet', 'violet'), ('wheat', 'wheat'), ('white', 'white'), ('whitesmoke', 'whitesmoke'), ('yellow', 'yellow'), ('yellowgreen', 'yellowgreen')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
