# Generated by Django 4.1.3 on 2023-03-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_item_image_main_alter_item_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
