# Generated by Django 4.1.3 on 2023-03-03 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0059_analysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name_plural': 'Analysis'},
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='visited_by',
        ),
        migrations.AddField(
            model_name='analysis',
            name='visited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
